### ISSUE TITLE
Add new constructor to Scarlet.Communications.Packet class

### ISSUE THREAD

**Issue by blobjim** [huskyroboticsteam/Scarlet#3]
It would be nice to have a Packet(bool id, bool isUDP, byte[] data, string endpoint = null) constructor so a packet can be created and initialized in a single expression.

**Comment by Baldstrom** [comment]
Thanks for your input! We will consider it for the next release of Scarlet. 

We thought about this already, we saw two sides: the downside is that people may think that the correct usage for the packet is to construct one for each message you send, when in reality you should only construct one packet for each packet ID you have. Obviously the advantage being that it is easier to construct one-time-use packets, like the packets we constantly construct in the beginning of the year teaching people how to use the API. 

But with the feedback, we will take another look! Feel free to add further feedback to this thread as well.

**Comment by CaiB** [comment]
Hi,

`Packet` has a constructor in the form of `Packet(Message Data, bool IsUDP, string Endpoint)` which is probably what you'd want.
To do this in code, you can currently write something like this:
`Packet Pack = new Packet(new Message(ID, Data), true, "YourClient");`

What do you think about this?

Regarding the other point that @Baldstrom made regarding Packet object reuse:
Funny enough this is not what I intended when designing Packet and Message, but everything in Scarlet should be able to handle you re-using Packet objects. I kind of implemented that as a just-in-case, and I just realized that this is what Jaden thought I was intending.
So you can either re-use Packet objects for different messages like he was suggesting, or you can create a new Packet object for every transmission (what I do and intended). Either should work fine.

**Comment by LouYu2015** [comment]
BTW, there's a new helper class called `PacketWriter` which is currently under review. After the code is merged and released, you can use `PacketWriter Writer = new PacketWriter(0x01).Put(str);`(replace `0x01` with your packet id and `str` with your data) to construct a packet and `Client.Send(Writer.Packet);` to send it.

**Comment by blobjim** [comment]
Does the endpoint address get fetched from a map and stored in the Packet? Why not just have a send method that takes a message, protocol, and endpoint as parameters? It feels a little bit cumbersome having both packets and messages.

**Comment by CaiB** [comment]
`Message` is meant as just the data in a packet, whereas the `Packet` object is a wrapper that then keeps all the other relevant metadata, such as destination and protocol, as well as the `Message` itself.
The `Packet` stores the `string` name of the endpoint, which the `Server` or `Client` will find an actual IP/port for when sending it.

We originally has them part of the same object, but early during development decided to split them like this because it made more sense to us architecturally.

As I showed above, you can create a packet with minimal extra code.
