### ISSUE TITLE
BME280 TestDataConvert Unit Test Failure

### ISSUE THREAD

**Issue by husky-robotics** [huskyroboticsteam/Scarlet#60]
Test Name:	TestDataConvert
Test FullName:	UnitTest.ComponentTesting.BME280Tests.TestDataConvert
Test Source:	C:\Users\natha\Documents\Scarlet\UnitTest\ComponentTesting\BME280Tests.cs : line 11
Test Outcome:	Failed
Test Duration:	0:00:00.1126659

Result StackTrace:	at UnitTest.ComponentTesting.BME280Tests.TestDataConvert() in C:\Users\natha\Documents\Scarlet\UnitTest\ComponentTesting\BME280Tests.cs:line 40
Result Message:	Assert.IsTrue failed.

**Comment by CaiB** [comment]
Fixed, I made a mistake when correcting a style issue, and misplaced some brackets.
